version: "3.7"

services:
    victim:
        build:
          context: .
          dockerfile: Dockerfile.victim
        container_name: victim
        privileged: true
        restart: always
        networks:
            - mitm

    attacker:
        build:
          context: .
          dockerfile: Dockerfile.attacker
        container_name: malcolm
        privileged: true
        networks:
            - mitm

networks:
    mitm:
