version: "3.7"

services:
    alice:
        image: jlesage/firefox
        container_name: mitm_alice
        restart: always
        networks:
            - mitm
    bob:
        image: aikain/simplehttpserver:0.1
        container_name: mitm_bob
        restart: always
        networks:
            - mitm
    eve:
        privileged: true
        build: .
        container_name: mitm_eve
        sysctls:
            # Necessary for transparent mode for mitmproxy
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
            - net.ipv4.conf.all.send_redirects=0
        networks:
            - mitm

networks:
    mitm:
