version: "3.7"

services:
    alice:
        build:
          context: .
          dockerfile: Dockerfile.victim
        container_name: alice
        privileged: true
        restart: always
        networks:
            - mitm

    bob:
        build:
          context: .
          dockerfile: Dockerfile.victim
        container_name: bob
        privileged: true
        restart: always
        networks:
            - mitm

    malcolm:
        build:
          context: .
          dockerfile: Dockerfile.attacker
        container_name: malcolm
        privileged: true
        networks:
            - mitm

networks:
    mitm:
