version: "3.7"

services:
    alice:
        image: jlesage/firefox
        container_name: alice
        restart: always
        networks:
            - mitm

    bob:
        image: aikain/simplehttpserver:0.1
        container_name: bob
        restart: always
        networks:
            - mitm

    malcolm:
        privileged: true
        build: .
        container_name: malcolm
        networks:
            - mitm

networks:
    mitm:
